// ============================================
// Exhaustive Test Suite: GUEST_CART
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for guest_cart', () => {

    // ─── ENDPOINT: POST /api/v1/guest/cart/add_promo ───

    test('GUEST_CART-1-POS-PERF: [Positive/Perf] Apply promo code to guest cart should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/guest/cart/add_promo`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: POST /api/v1/guest/cart/add ───

    test('GUEST_CART-2-POS-PERF: [Positive/Perf] Add item to guest cart should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/guest/cart/add`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/guest/cart/i ───

    test('GUEST_CART-3-POS-PERF: [Positive/Perf] Get current guest cart should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/i`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-3-SEC-SQL: [Security] Get current guest cart should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/i?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-3-BND-PAG: [Boundary] Get current guest cart should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/cart/i'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/i${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: POST /api/v1/guest/cart/i/choose/payment ───

    test('GUEST_CART-4-POS-PERF: [Positive/Perf] Choose payment method for current guest cart should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/guest/cart/i/choose/payment`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/guest/cart/{item_id}/delete ───

    test('GUEST_CART-5-POS-PERF: [Positive/Perf] Delete item from guest cart should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/1/delete`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-5-SEC-SQL: [Security] Delete item from guest cart should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/${SQL_INJECTION_PAYLOADS[0]}/delete`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-5-BND-PAG: [Boundary] Delete item from guest cart should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/cart/1/delete'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/1/delete${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/guest/cart/{item_id}/restore ───

    test('GUEST_CART-6-POS-PERF: [Positive/Perf] Restore item to guest cart should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/1/restore`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-6-SEC-SQL: [Security] Restore item to guest cart should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/${SQL_INJECTION_PAYLOADS[0]}/restore`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-6-BND-PAG: [Boundary] Restore item to guest cart should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/cart/1/restore'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/1/restore${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: POST /api/v1/guest/cart/i/complet ───

    test('GUEST_CART-7-POS-PERF: [Positive/Perf] Complete guest cart into an order should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/guest/cart/i/complet`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/guest/cart/available_times ───

    test('GUEST_CART-8-POS-PERF: [Positive/Perf] Get available times for booking should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/available_times`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-8-SEC-SQL: [Security] Get available times for booking should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/available_times?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-8-BND-PAG: [Boundary] Get available times for booking should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/cart/available_times'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/available_times${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/guest/cart/closed_days ───

    test('GUEST_CART-9-POS-PERF: [Positive/Perf] Get closed days for booking should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/closed_days`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-9-SEC-SQL: [Security] Get closed days for booking should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/closed_days?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_CART-9-BND-PAG: [Boundary] Get closed days for booking should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/cart/closed_days'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/cart/closed_days${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
