// ============================================
// Exhaustive Test Suite: ADMIN_BLOGS
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for admin_blogs', () => {

    // ─── ENDPOINT: GET /api/v1/admin/blogs ───

    test('ADMIN_BLOGS-1-POS-PERF: [Positive/Perf] Get all blogs should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_BLOGS-1-NEG-AUTH: [Negative/Auth] Get all blogs should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_BLOGS-1-SEC-SQL: [Security] Get all blogs should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADMIN_BLOGS-1-BND-PAG: [Boundary] Get all blogs should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/admin/blogs'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: POST /api/v1/admin/blogs ───

    test('ADMIN_BLOGS-2-POS-PERF: [Positive/Perf] Create blog (all users) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/admin/blogs`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_BLOGS-2-NEG-AUTH: [Negative/Auth] Create blog (all users) should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/admin/blogs`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    // ─── ENDPOINT: GET /api/v1/admin/blogs/{id} ───

    test('ADMIN_BLOGS-3-POS-PERF: [Positive/Perf] Get blog by id should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_BLOGS-3-NEG-AUTH: [Negative/Auth] Get blog by id should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_BLOGS-3-SEC-SQL: [Security] Get blog by id should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADMIN_BLOGS-3-BND-PAG: [Boundary] Get blog by id should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/admin/blogs/1'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/blogs/1${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: PUT /api/v1/admin/blogs/{id} ───

    test('ADMIN_BLOGS-4-POS-PERF: [Positive/Perf] Update blog should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.put(`${BASE_URL}/api/v1/admin/blogs/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_BLOGS-4-NEG-AUTH: [Negative/Auth] Update blog should reject missing auth', async ({ request }) => {
        const response = await request.put(`${BASE_URL}/api/v1/admin/blogs/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_BLOGS-4-SEC-SQL: [Security] Update blog should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.put(`${BASE_URL}/api/v1/admin/blogs/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: DELETE /api/v1/admin/blogs/{id} ───

    test('ADMIN_BLOGS-5-POS-PERF: [Positive/Perf] Delete blog should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.delete(`${BASE_URL}/api/v1/admin/blogs/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_BLOGS-5-NEG-AUTH: [Negative/Auth] Delete blog should reject missing auth', async ({ request }) => {
        const response = await request.delete(`${BASE_URL}/api/v1/admin/blogs/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_BLOGS-5-SEC-SQL: [Security] Delete blog should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.delete(`${BASE_URL}/api/v1/admin/blogs/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

});
