// ============================================
// Exhaustive Test Suite: BANKS_SET-DEFAULT
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for banks_set-default', () => {

    // ─── ENDPOINT: GET /api/v1/bank-accounts/{id}/set-default ───

    test('BANKS_SET-DEFAULT-1-POS-PERF: [Positive/Perf] Set a bank account as default should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/bank-accounts/1/set-default`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('BANKS_SET-DEFAULT-1-NEG-AUTH: [Negative/Auth] Set a bank account as default should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/bank-accounts/1/set-default`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('BANKS_SET-DEFAULT-1-SEC-SQL: [Security] Set a bank account as default should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/bank-accounts/${SQL_INJECTION_PAYLOADS[0]}/set-default`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('BANKS_SET-DEFAULT-1-BND-PAG: [Boundary] Set a bank account as default should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/bank-accounts/1/set-default'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/bank-accounts/1/set-default${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
