// ============================================
// Exhaustive Test Suite: AUTH_RESET-PASSWORD
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for auth_reset-password', () => {

    // ─── ENDPOINT: POST /api/v1/auth/reset-password/{token} ───

    test('AUTH_RESET-PASSWORD-1-POS-PERF: [Positive/Perf] Reset Password should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/auth/reset-password/1`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('AUTH_RESET-PASSWORD-1-SEC-SQL: [Security] Reset Password should handle SQL injection safely', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/auth/reset-password/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
