// ============================================
// Exhaustive Test Suite: CATEGORIES
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for categories', () => {

    // ─── ENDPOINT: GET /api/v1/categories ───

    test('CATEGORIES-1-POS-PERF: [Positive/Perf] All categories should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/categories`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('CATEGORIES-1-SEC-SQL: [Security] All categories should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/categories?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('CATEGORIES-1-BND-PAG: [Boundary] All categories should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/categories'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/categories${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
