// ============================================
// Exhaustive Test Suite: CART_I
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for cart_i', () => {

    // ─── ENDPOINT: GET /api/v1/cart/i ───

    test('CART_I-1-POS-PERF: [Positive/Perf] Get current customer cart should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/cart/i`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('CART_I-1-NEG-AUTH: [Negative/Auth] Get current customer cart should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/cart/i`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('CART_I-1-SEC-SQL: [Security] Get current customer cart should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/cart/i?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('CART_I-1-BND-PAG: [Boundary] Get current customer cart should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/cart/i'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/cart/i${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: POST /api/v1/cart/i/choose/payment ───

    test('CART_I-2-POS-PERF: [Positive/Perf] Choose payment method for current cart should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/cart/i/choose/payment`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('CART_I-2-NEG-AUTH: [Negative/Auth] Choose payment method for current cart should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/cart/i/choose/payment`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    // ─── ENDPOINT: POST /api/v1/cart/i/complet ───

    test('CART_I-3-POS-PERF: [Positive/Perf] Complete current cart into an order should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/cart/i/complet`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('CART_I-3-NEG-AUTH: [Negative/Auth] Complete current cart into an order should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/cart/i/complet`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

});
