// ============================================
// Exhaustive Test Suite: THANKS
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for thanks', () => {

    // ─── ENDPOINT: GET /api/v1/thanks ───

    test('THANKS-1-POS-PERF: [Positive/Perf] Tap payment redirect landing page should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/thanks`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('THANKS-1-SEC-SQL: [Security] Tap payment redirect landing page should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/thanks?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    test('THANKS-1-BND-PAG: [Boundary] Tap payment redirect landing page should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/thanks'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/thanks${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

});
