// ============================================
// Exhaustive Test Suite: SALON_SERVICES
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for salon_services', () => {

    // ─── ENDPOINT: GET /api/v1/salon/services ───

    test('SALON_SERVICES-1-POS-PERF: [Positive/Perf] List own services should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/salon/services`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_SERVICES-1-NEG-AUTH: [Negative/Auth] List own services should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/salon/services`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('SALON_SERVICES-1-SEC-SQL: [Security] List own services should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/salon/services?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('SALON_SERVICES-1-BND-PAG: [Boundary] List own services should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/salon/services'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/salon/services${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: POST /api/v1/salon/services/create ───

    test('SALON_SERVICES-2-POS-PERF: [Positive/Perf] Create service (mobile) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/salon/services/create`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_SERVICES-2-NEG-AUTH: [Negative/Auth] Create service (mobile) should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/salon/services/create`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    // ─── ENDPOINT: DELETE /api/v1/salon/services/{id}/delete ───

    test('SALON_SERVICES-3-POS-PERF: [Positive/Perf] Delete service (mobile) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.delete(`${BASE_URL}/api/v1/salon/services/1/delete`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_SERVICES-3-NEG-AUTH: [Negative/Auth] Delete service (mobile) should reject missing auth', async ({ request }) => {
        const response = await request.delete(`${BASE_URL}/api/v1/salon/services/1/delete`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('SALON_SERVICES-3-SEC-SQL: [Security] Delete service (mobile) should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.delete(`${BASE_URL}/api/v1/salon/services/${SQL_INJECTION_PAYLOADS[0]}/delete`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: POST /api/v1/salon/services/{id}/restore ───

    test('SALON_SERVICES-4-POS-PERF: [Positive/Perf] Restore a deleted service (mobile) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/salon/services/1/restore`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_SERVICES-4-NEG-AUTH: [Negative/Auth] Restore a deleted service (mobile) should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/salon/services/1/restore`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('SALON_SERVICES-4-SEC-SQL: [Security] Restore a deleted service (mobile) should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.post(`${BASE_URL}/api/v1/salon/services/${SQL_INJECTION_PAYLOADS[0]}/restore`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

});
