// ============================================
// Exhaustive Test Suite: GUEST_PACKAGES
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for guest_packages', () => {

    // ─── ENDPOINT: GET /api/v1/guest/packages ───

    test('GUEST_PACKAGES-1-POS-PERF: [Positive/Perf] Public package listing should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/packages`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_PACKAGES-1-SEC-SQL: [Security] Public package listing should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/packages?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_PACKAGES-1-BND-PAG: [Boundary] Public package listing should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/packages'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/packages${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/guest/packages/{id}/show ───

    test('GUEST_PACKAGES-2-POS-PERF: [Positive/Perf] Get package details (guest) should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/packages/1/show`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_PACKAGES-2-SEC-SQL: [Security] Get package details (guest) should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/packages/${SQL_INJECTION_PAYLOADS[0]}/show`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('GUEST_PACKAGES-2-BND-PAG: [Boundary] Get package details (guest) should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/packages/1/show'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/packages/1/show${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
