// ============================================
// Exhaustive Test Suite: BALANCE_NEW
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for balance_new', () => {

    // ─── ENDPOINT: POST /api/v1/balance/new ───

    test('BALANCE_NEW-1-POS-PERF: [Positive/Perf] Initiate wallet top-up via Tap (card or Apple Pay source) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/balance/new`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('BALANCE_NEW-1-NEG-AUTH: [Negative/Auth] Initiate wallet top-up via Tap (card or Apple Pay source) should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/balance/new`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

});
