// ============================================
// Exhaustive Test Suite: SALONS_OFFERS
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for salons_offers', () => {

    // ─── ENDPOINT: GET /api/v1/salons/{salon_id}/offers ───

    test('SALONS_OFFERS-1-POS-PERF: [Positive/Perf] List salon offers should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/salons/1/offers`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALONS_OFFERS-1-NEG-AUTH: [Negative/Auth] List salon offers should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/salons/1/offers`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('SALONS_OFFERS-1-SEC-SQL: [Security] List salon offers should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/salons/${SQL_INJECTION_PAYLOADS[0]}/offers`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('SALONS_OFFERS-1-BND-PAG: [Boundary] List salon offers should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/salons/1/offers'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/salons/1/offers${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

});
