// ============================================
// Exhaustive Test Suite: ADMIN_PROMOCODES
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for admin_promocodes', () => {

    // ─── ENDPOINT: GET /api/v1/admin/promocodes ───

    test('ADMIN_PROMOCODES-1-POS-PERF: [Positive/Perf] List all promocodes (paginated) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PROMOCODES-1-NEG-AUTH: [Negative/Auth] List all promocodes (paginated) should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PROMOCODES-1-SEC-SQL: [Security] List all promocodes (paginated) should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADMIN_PROMOCODES-1-BND-PAG: [Boundary] List all promocodes (paginated) should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/admin/promocodes'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: POST /api/v1/admin/promocodes ───

    test('ADMIN_PROMOCODES-2-POS-PERF: [Positive/Perf] Create promocode (all users) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/admin/promocodes`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PROMOCODES-2-NEG-AUTH: [Negative/Auth] Create promocode (all users) should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/admin/promocodes`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    // ─── ENDPOINT: POST /api/v1/admin/promocodes/user/{userId} ───

    test('ADMIN_PROMOCODES-3-POS-PERF: [Positive/Perf] Create promocode for specific user should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/admin/promocodes/user/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PROMOCODES-3-NEG-AUTH: [Negative/Auth] Create promocode for specific user should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/admin/promocodes/user/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PROMOCODES-3-SEC-SQL: [Security] Create promocode for specific user should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.post(`${BASE_URL}/api/v1/admin/promocodes/user/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: GET /api/v1/admin/promocodes/{id} ───

    test('ADMIN_PROMOCODES-4-POS-PERF: [Positive/Perf] Get a promocode by id should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PROMOCODES-4-NEG-AUTH: [Negative/Auth] Get a promocode by id should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PROMOCODES-4-SEC-SQL: [Security] Get a promocode by id should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADMIN_PROMOCODES-4-BND-PAG: [Boundary] Get a promocode by id should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/admin/promocodes/1'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/promocodes/1${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: PATCH /api/v1/admin/promocodes/{id} ───

    test('ADMIN_PROMOCODES-5-POS-PERF: [Positive/Perf] Update a promocode should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.patch(`${BASE_URL}/api/v1/admin/promocodes/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PROMOCODES-5-NEG-AUTH: [Negative/Auth] Update a promocode should reject missing auth', async ({ request }) => {
        const response = await request.patch(`${BASE_URL}/api/v1/admin/promocodes/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PROMOCODES-5-SEC-SQL: [Security] Update a promocode should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.patch(`${BASE_URL}/api/v1/admin/promocodes/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: DELETE /api/v1/admin/promocodes/{id} ───

    test('ADMIN_PROMOCODES-6-POS-PERF: [Positive/Perf] Delete a promocode should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.delete(`${BASE_URL}/api/v1/admin/promocodes/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PROMOCODES-6-NEG-AUTH: [Negative/Auth] Delete a promocode should reject missing auth', async ({ request }) => {
        const response = await request.delete(`${BASE_URL}/api/v1/admin/promocodes/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PROMOCODES-6-SEC-SQL: [Security] Delete a promocode should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.delete(`${BASE_URL}/api/v1/admin/promocodes/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

});
