// ============================================
// Exhaustive Test Suite: AUTH_GOOGLE
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for auth_google', () => {

    // ─── ENDPOINT: POST /api/v1/auth/google/login ───

    test('AUTH_GOOGLE-1-POS-PERF: [Positive/Perf] POST /api/v1/auth/google/login should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/auth/google/login`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

});
