// ============================================
// Exhaustive Test Suite: SALON_PROFILE
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for salon_profile', () => {

    // ─── ENDPOINT: GET /api/v1/salon/profile/files ───

    test('SALON_PROFILE-1-POS-PERF: [Positive/Perf] Get authenticated salon uploaded files (SalonInfo records) should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/files`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_PROFILE-1-NEG-AUTH: [Negative/Auth] Get authenticated salon uploaded files (SalonInfo records) should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/files`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('SALON_PROFILE-1-SEC-SQL: [Security] Get authenticated salon uploaded files (SalonInfo records) should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/files?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('SALON_PROFILE-1-BND-PAG: [Boundary] Get authenticated salon uploaded files (SalonInfo records) should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/salon/profile/files'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/files${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: GET /api/v1/salon/profile/working-days ───

    test('SALON_PROFILE-2-POS-PERF: [Positive/Perf] Get authenticated salon working days should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/working-days`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_PROFILE-2-NEG-AUTH: [Negative/Auth] Get authenticated salon working days should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/working-days`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('SALON_PROFILE-2-SEC-SQL: [Security] Get authenticated salon working days should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/working-days?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('SALON_PROFILE-2-BND-PAG: [Boundary] Get authenticated salon working days should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/salon/profile/working-days'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/salon/profile/working-days${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: PUT /api/v1/salon/profile/working-days ───

    test('SALON_PROFILE-3-POS-PERF: [Positive/Perf] Replace working days for authenticated salon should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.put(`${BASE_URL}/api/v1/salon/profile/working-days`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('SALON_PROFILE-3-NEG-AUTH: [Negative/Auth] Replace working days for authenticated salon should reject missing auth', async ({ request }) => {
        const response = await request.put(`${BASE_URL}/api/v1/salon/profile/working-days`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

});
