// ============================================
// Exhaustive Test Suite: ADDRESS_DELETE
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for address_delete', () => {

    // ─── ENDPOINT: GET /api/v1/address/{id}/delete ───

    test('ADDRESS_DELETE-1-POS-PERF: [Positive/Perf] Delete an address should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/address/1/delete`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADDRESS_DELETE-1-NEG-AUTH: [Negative/Auth] Delete an address should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/address/1/delete`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADDRESS_DELETE-1-SEC-SQL: [Security] Delete an address should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/address/${SQL_INJECTION_PAYLOADS[0]}/delete`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADDRESS_DELETE-1-BND-PAG: [Boundary] Delete an address should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/address/1/delete'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/address/1/delete${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

});
