// ============================================
// Exhaustive Test Suite: OFFERS_SHOW
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for offers_show', () => {

    // ─── ENDPOINT: GET /api/v1/offers/{id}/show ───

    test('OFFERS_SHOW-1-POS-PERF: [Positive/Perf] Get offer details should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/offers/1/show`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('OFFERS_SHOW-1-NEG-AUTH: [Negative/Auth] Get offer details should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/offers/1/show`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('OFFERS_SHOW-1-SEC-SQL: [Security] Get offer details should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/offers/${SQL_INJECTION_PAYLOADS[0]}/show`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('OFFERS_SHOW-1-BND-PAG: [Boundary] Get offer details should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/offers/1/show'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/offers/1/show${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
