// ============================================
// Exhaustive Test Suite: CART_ADD
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for cart_add', () => {

    // ─── ENDPOINT: POST /api/v1/cart/add ───

    test('CART_ADD-1-POS-PERF: [Positive/Perf] Add item to cart should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/cart/add`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('CART_ADD-1-NEG-AUTH: [Negative/Auth] Add item to cart should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/cart/add`, {
            headers: MOBILE_HEADERS
        });
        expect([200, 400, 401, 403, 404, 422]).toContain(response.status());
    });

});
