// ============================================
// Exhaustive Test Suite: AUTH_ADMIN
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for auth_admin', () => {

    // ─── ENDPOINT: POST /api/v1/auth/admin/login ───

    test('AUTH_ADMIN-1-POS-PERF: [Positive/Perf] Admin and Provider Login should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/auth/admin/login`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    // ─── ENDPOINT: POST /api/v1/auth/admin/refresh ───

    test('AUTH_ADMIN-2-POS-PERF: [Positive/Perf] Refresh Token should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/auth/admin/refresh`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('AUTH_ADMIN-2-NEG-AUTH: [Negative/Auth] Refresh Token should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/auth/admin/refresh`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

});
