// ============================================
// Exhaustive Test Suite: GUEST_SERVICES_TYPES
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for guest_services_types', () => {

    // ─── ENDPOINT: GET /api/v1/guest/services_types/{type} ───

    test('GUEST_SERVICES_TYPES-1-POS-PERF: [Positive/Perf] Get service types should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/services_types/1`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('GUEST_SERVICES_TYPES-1-SEC-SQL: [Security] Get service types should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/services_types/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    test('GUEST_SERVICES_TYPES-1-BND-PAG: [Boundary] Get service types should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/services_types/1'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/services_types/1${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

});
