// ============================================
// Exhaustive Test Suite: ADMIN_PACKAGE-ADVERTISEMENTS
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for admin_package-advertisements', () => {

    // ─── ENDPOINT: GET /api/v1/admin/package-advertisements ───

    test('ADMIN_PACKAGE-ADVERTISEMENTS-1-POS-PERF: [Positive/Perf] Get all package advertisements should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-1-NEG-AUTH: [Negative/Auth] Get all package advertisements should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-1-SEC-SQL: [Security] Get all package advertisements should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-1-BND-PAG: [Boundary] Get all package advertisements should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/admin/package-advertisements'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: POST /api/v1/admin/package-advertisements ───

    test('ADMIN_PACKAGE-ADVERTISEMENTS-2-POS-PERF: [Positive/Perf] Create package advertisement should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.post(`${BASE_URL}/api/v1/admin/package-advertisements`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-2-NEG-AUTH: [Negative/Auth] Create package advertisement should reject missing auth', async ({ request }) => {
        const response = await request.post(`${BASE_URL}/api/v1/admin/package-advertisements`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    // ─── ENDPOINT: GET /api/v1/admin/package-advertisements/{id} ───

    test('ADMIN_PACKAGE-ADVERTISEMENTS-3-POS-PERF: [Positive/Perf] Get package advertisement by id should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-3-NEG-AUTH: [Negative/Auth] Get package advertisement by id should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-3-SEC-SQL: [Security] Get package advertisement by id should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-3-BND-PAG: [Boundary] Get package advertisement by id should handle extreme pagination', async ({ request }) => {
        const token = await getUserToken(request);
        const separator = '/api/v1/admin/package-advertisements/1'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/package-advertisements/1${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: PUT /api/v1/admin/package-advertisements/{id} ───

    test('ADMIN_PACKAGE-ADVERTISEMENTS-4-POS-PERF: [Positive/Perf] Update package advertisement should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.put(`${BASE_URL}/api/v1/admin/package-advertisements/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-4-NEG-AUTH: [Negative/Auth] Update package advertisement should reject missing auth', async ({ request }) => {
        const response = await request.put(`${BASE_URL}/api/v1/admin/package-advertisements/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-4-SEC-SQL: [Security] Update package advertisement should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.put(`${BASE_URL}/api/v1/admin/package-advertisements/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: DELETE /api/v1/admin/package-advertisements/{id} ───

    test('ADMIN_PACKAGE-ADVERTISEMENTS-5-POS-PERF: [Positive/Perf] Delete package advertisement should respond under 2000ms', async ({ request }) => {
        const token = await getUserToken(request);
        const start = Date.now();
        const response = await request.delete(`${BASE_URL}/api/v1/admin/package-advertisements/1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-5-NEG-AUTH: [Negative/Auth] Delete package advertisement should reject missing auth', async ({ request }) => {
        const response = await request.delete(`${BASE_URL}/api/v1/admin/package-advertisements/1`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_PACKAGE-ADVERTISEMENTS-5-SEC-SQL: [Security] Delete package advertisement should handle SQL injection safely', async ({ request }) => {
        const token = await getUserToken(request);
        const response = await request.delete(`${BASE_URL}/api/v1/admin/package-advertisements/${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect(response.status()).not.toBe(500);
    });

});
