// ============================================
// Exhaustive Test Suite: GUEST_SALONS
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for guest_salons', () => {

    // ─── ENDPOINT: GET /api/v1/guest/salons ───

    test('GUEST_SALONS-1-POS-PERF: [Positive/Perf] Public salon listing (no auth required) should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('GUEST_SALONS-1-SEC-SQL: [Security] Public salon listing (no auth required) should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    test('GUEST_SALONS-1-BND-PAG: [Boundary] Public salon listing (no auth required) should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/salons'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: GET /api/v1/guest/salons/best ───

    test('GUEST_SALONS-2-POS-PERF: [Positive/Perf] Best / featured salons, optionally filtered by country should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons/best`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('GUEST_SALONS-2-SEC-SQL: [Security] Best / featured salons, optionally filtered by country should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons/best?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    test('GUEST_SALONS-2-BND-PAG: [Boundary] Best / featured salons, optionally filtered by country should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/salons/best'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons/best${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    // ─── ENDPOINT: GET /api/v1/guest/salons/{salon_id}/offers ───

    test('GUEST_SALONS-3-POS-PERF: [Positive/Perf] List salon offers (guest) should respond under 2000ms', async ({ request }) => {
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons/1/offers`, {
            headers: { ...MOBILE_HEADERS }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());
    });

    test('GUEST_SALONS-3-SEC-SQL: [Security] List salon offers (guest) should handle SQL injection safely', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons/${SQL_INJECTION_PAYLOADS[0]}/offers`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

    test('GUEST_SALONS-3-BND-PAG: [Boundary] List salon offers (guest) should handle extreme pagination', async ({ request }) => {
        const separator = '/api/v1/guest/salons/1/offers'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/guest/salons/1/offers${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS }
        });
        expect(response.status()).not.toBe(500);
    });

});
