// ============================================
// Exhaustive Test Suite: ADMIN_CONTACT_US
// Auto-generated by MyCoifeur Test Generator
// ============================================

const { test, expect } = require('@playwright/test');
const { BASE_URL, MOBILE_HEADERS, getAdminToken } = require("../helpers/auth.helper");
const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');

test.describe('Exhaustive Tests for admin_contact_us', () => {

    // ─── ENDPOINT: GET /api/v1/admin/contact_us ───

    test('ADMIN_CONTACT_US-1-POS-PERF: [Positive/Perf] Get all contact us messages should respond under 2000ms', async ({ request }) => {
        const token = await getAdminToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('ADMIN_CONTACT_US-1-NEG-AUTH: [Negative/Auth] Get all contact us messages should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_CONTACT_US-1-SEC-SQL: [Security] Get all contact us messages should handle SQL injection safely', async ({ request }) => {
        const token = await getAdminToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us?q=${SQL_INJECTION_PAYLOADS[0]}`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('ADMIN_CONTACT_US-1-BND-PAG: [Boundary] Get all contact us messages should handle extreme pagination', async ({ request }) => {
        const token = await getAdminToken(request);
        const separator = '/api/v1/admin/contact_us'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: GET /api/v1/admin/contact_us/{id}/show ───

    test('ADMIN_CONTACT_US-2-POS-PERF: [Positive/Perf] Get contact us by id should respond under 2000ms', async ({ request }) => {
        const token = await getAdminToken(request);
        const start = Date.now();
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us/1/show`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('ADMIN_CONTACT_US-2-NEG-AUTH: [Negative/Auth] Get contact us by id should reject missing auth', async ({ request }) => {
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us/1/show`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_CONTACT_US-2-SEC-SQL: [Security] Get contact us by id should handle SQL injection safely', async ({ request }) => {
        const token = await getAdminToken(request);
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us/${SQL_INJECTION_PAYLOADS[0]}/show`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('ADMIN_CONTACT_US-2-BND-PAG: [Boundary] Get contact us by id should handle extreme pagination', async ({ request }) => {
        const token = await getAdminToken(request);
        const separator = '/api/v1/admin/contact_us/1/show'.includes('?') ? '&' : '?';
        const response = await request.get(`${BASE_URL}/api/v1/admin/contact_us/1/show${separator}limit=99999&page=-1`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    // ─── ENDPOINT: DELETE /api/v1/admin/contact_us/{id}/delete ───

    test('ADMIN_CONTACT_US-3-POS-PERF: [Positive/Perf] Delete contact us message should respond under 2000ms', async ({ request }) => {
        const token = await getAdminToken(request);
        const start = Date.now();
        const response = await request.delete(`${BASE_URL}/api/v1/admin/contact_us/1/delete`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        const duration = Date.now() - start;
        // Performance expectation removed per user request.
        // Note: Accepting multiple statuses as this is a generic generator
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

    test('ADMIN_CONTACT_US-3-NEG-AUTH: [Negative/Auth] Delete contact us message should reject missing auth', async ({ request }) => {
        const response = await request.delete(`${BASE_URL}/api/v1/admin/contact_us/1/delete`, {
            headers: MOBILE_HEADERS
        });
        expect(response.status()).toBeGreaterThanOrEqual(401);
    });

    test('ADMIN_CONTACT_US-3-SEC-SQL: [Security] Delete contact us message should handle SQL injection safely', async ({ request }) => {
        const token = await getAdminToken(request);
        const response = await request.delete(`${BASE_URL}/api/v1/admin/contact_us/${SQL_INJECTION_PAYLOADS[0]}/delete`, {
            headers: { ...MOBILE_HEADERS, 'Authorization': `Bearer ${token}` }
        });
        expect([200, 201, 204, 400, 401, 403, 404, 422, 500]).toContain(response.status());
    });

});
