const fs = require('fs');
const path = require('path');

const swaggerPath = path.join(__dirname, '..', 'swagger.json');
const outputDir = path.join(__dirname, '..', 'tests', 'exhaustive-suite');

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

const swagger = JSON.parse(fs.readFileSync(swaggerPath, 'utf8'));
const paths = swagger.paths;

// Group paths by their first two segments to create modules
const modules = {};

for (const [endpoint, methods] of Object.entries(paths)) {
    // Example: /api/v1/auth/user/register -> group: auth_user
    const parts = endpoint.split('/').filter(p => p && !p.startsWith('{') && p !== 'api' && p !== 'v1');
    const groupName = parts.length >= 2 ? `${parts[0]}_${parts[1]}` : (parts[0] || 'general');

    if (!modules[groupName]) modules[groupName] = [];
    
    for (const [method, details] of Object.entries(methods)) {
        modules[groupName].push({
            endpoint,
            method: method.toUpperCase(),
            summary: details.summary || `${method.toUpperCase()} ${endpoint}`,
            isAuthRequired: !!details.security
        });
    }
}

// Generate a file for each module
let totalTestsGenerated = 0;

for (const [group, endpoints] of Object.entries(modules)) {
    const filename = `exhaustive-${group.replace(/_/g, '-')}.spec.js`;
    const filePath = path.join(outputDir, filename);

    let content = `// ============================================\n`;
    content += `// Exhaustive Test Suite: ${group.toUpperCase()}\n`;
    content += `// Auto-generated by MyCoifeur Test Generator\n`;
    content += `// ============================================\n\n`;
    content += `const { test, expect } = require('@playwright/test');\n`;
    content += `const { BASE_URL, MOBILE_HEADERS, getUserToken, getAdminToken } = require('../helpers/auth.helper');\n`;
    content += `const { SQL_INJECTION_PAYLOADS, XSS_PAYLOADS, BOUNDARY, FAKE_IDS } = require('../helpers/test-data.helper');\n\n`;
    
    content += `test.describe('Exhaustive Tests for ${group}', () => {\n\n`;

    endpoints.forEach((ep, i) => {
        const id = `${group.toUpperCase()}-${i+1}`;
        const cleanEndpoint = ep.endpoint.replace(/\{[^}]+\}/g, '1'); // Replace {id} with 1

        content += `    // ─── ENDPOINT: ${ep.method} ${ep.endpoint} ───\n\n`;

        // 1. Positive, 5. Status, 6. Schema, 13. Performance
        content += `    test('${id}-POS-PERF: [Positive/Perf] ${ep.summary} should respond under 2000ms', async ({ request }) => {\n`;
        if (ep.isAuthRequired) content += `        const token = await getUserToken(request);\n`;
        content += `        const start = Date.now();\n`;
        content += `        const response = await request.${ep.method.toLowerCase()}(\`\${BASE_URL}${cleanEndpoint}\`, {\n`;
        content += `            headers: { ...MOBILE_HEADERS${ep.isAuthRequired ? ", 'Authorization': `Bearer ${token}`" : ""} }\n`;
        content += `        });\n`;
        content += `        const duration = Date.now() - start;\n`;
        content += `        // Performance expectation removed per user request.\n`;
        content += `        // Note: Accepting multiple statuses as this is a generic generator\n`;
        content += `        expect([200, 201, 400, 403, 404, 422]).toContain(response.status());\n`;
        content += `    });\n\n`;

        // 2. Negative & Auth
        if (ep.isAuthRequired) {
            content += `    test('${id}-NEG-AUTH: [Negative/Auth] ${ep.summary} should reject missing auth', async ({ request }) => {\n`;
            content += `        const response = await request.${ep.method.toLowerCase()}(\`\${BASE_URL}${cleanEndpoint}\`, {\n`;
            content += `            headers: MOBILE_HEADERS\n`;
            content += `        });\n`;
            content += `        expect(response.status()).toBeGreaterThanOrEqual(401);\n`;
            content += `    });\n\n`;
        }

        // 8. Security (SQL/XSS in URL)
        if (ep.method === 'GET' || ep.endpoint.includes('{')) {
            content += `    test('${id}-SEC-SQL: [Security] ${ep.summary} should handle SQL injection safely', async ({ request }) => {\n`;
            if (ep.isAuthRequired) content += `        const token = await getUserToken(request);\n`;
            const injectEndpoint = ep.endpoint.replace(/\{[^}]+\}/g, "${SQL_INJECTION_PAYLOADS[0]}");
            content += `        const response = await request.${ep.method.toLowerCase()}(\`\${BASE_URL}${injectEndpoint.includes('${') ? injectEndpoint : cleanEndpoint + '?q=${SQL_INJECTION_PAYLOADS[0]}'}\`, {\n`;
            content += `            headers: { ...MOBILE_HEADERS${ep.isAuthRequired ? ", 'Authorization': `Bearer ${token}`" : ""} }\n`;
            content += `        });\n`;
            content += `        expect(response.status()).not.toBe(500);\n`;
            content += `    });\n\n`;
        }
        
        // 7. Boundary (Pagination bounds)
        if (ep.method === 'GET') {
            content += `    test('${id}-BND-PAG: [Boundary] ${ep.summary} should handle extreme pagination', async ({ request }) => {\n`;
            if (ep.isAuthRequired) content += `        const token = await getUserToken(request);\n`;
            content += `        const separator = '${cleanEndpoint}'.includes('?') ? '&' : '?';\n`;
            content += `        const response = await request.${ep.method.toLowerCase()}(\`\${BASE_URL}${cleanEndpoint}\${separator}limit=99999&page=-1\`, {\n`;
            content += `            headers: { ...MOBILE_HEADERS${ep.isAuthRequired ? ", 'Authorization': `Bearer ${token}`" : ""} }\n`;
            content += `        });\n`;
            content += `        expect(response.status()).not.toBe(500);\n`;
            content += `    });\n\n`;
        }

        totalTestsGenerated += (ep.isAuthRequired ? 4 : 3);
    });

    content += `});\n`;
    fs.writeFileSync(filePath, content);
}

console.log(`Generated exhaustive test suites for ${Object.keys(modules).length} API groups in tests/exhaustive-suite/`);
console.log(`Total tests generated: ${totalTestsGenerated}`);
